name: qiliblog

services:
  db:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    networks:
      - default
    environment:
      MYSQL_DATABASE: qiliblog
      MYSQL_USER: qiliblog
      MYSQL_PASSWORD: qiliblog001
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
  redis:
    image: bitnami/redis:6.2.16
    ports:
      - "6379:6379"
    networks:
      - default
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  mysql_data:
  redis_data:

networks:
  default: