spring:
  datasource:
    username: ${DB_USER:qiliblog}
    password: ${DB_PASSWORD:qiliblog001}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/qiliblog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

  mail:
    username:  # 邮箱
    password:  # 授权码

logging:
  level:
    com.zqqiliyc: info
    web: info
    root: warn
    sql: error
  logback:
    rollingpolicy:
      clean-history-on-start: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
