spring:
  datasource:
    username: qiliblog
    password: qiliblog001
    url: jdbc:mysql://localhost:3306/qiliblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

logging:
  level:
    com.zqqiliyc: debug
    web: debug
    sql: info
    org.springframework.transaction: info
    org.springframework.jdbc: info
    org.springframework.dao: info
    org.apache.shiro: debug
    org.springframework.security: debug
#    org.springframework.aop: trace
#    org.springframework.cglib: trace
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl