spring:
  docker:
    compose:
      enabled: true
  datasource:
    username: qiliblog
    password: qiliblog001
    url: jdbc:mysql://localhost:3306/qiliblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

logging:
  level:
    com.zqqiliyc: debug
    web: debug
    sql: debug
    org.springframework.transaction: trace
    org.springframework.jdbc: trace
    org.springframework.dao: trace
#    org.springframework.aop: trace
#    org.springframework.cglib: trace
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl