spring:
  docker:
    compose:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: qiliblog
    password: qiliblog001
    url: jdbc:mysql://localhost:3306/qiliblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    hikari:
      auto-commit: false

mybatis-plus:
  # mybatis 的原生配置
  configuration:
    auto-mapping-behavior: partial # full，会自动映射，这里设置为partial，只映射一部分
    default-fetch-size: 100 # 为驱动的结果集获取数量（fetchSize）设置一个建议值。此参数只可以在查询设置中被覆盖。
    map-underscore-to-camel-case: true # 是否开启驼峰命名自动映射，即从经典数据库列名 A_COLUMN 映射到经典 Java 属性名 aColumn。
    shrink-whitespaces-in-sql: true # 是否在 SQL 中删除多余的空白。请注意，这也会影响SQL中的文字字符串。
    arg-name-based-constructor-auto-mapping: true # 是否基于参数名称自动映射构造函数参数。
  type-aliases-package: com.zqqiliyc.domain.entity
  type-aliases-super-type: com.zqqiliyc.domain.entity.BaseEntity
  global-config:
    banner: false # 是否显示banner
    db-config:
      id-type: assign_id # 主键生成策略 默认雪花算法
      logic-delete-field: del_flag # 逻辑删除字段名 仅在逻辑删除功能打开时有效。