spring:
  docker:
    compose:
      enabled: false
  datasource:
    username: qiliblog
    password: qiliblog001
    url: jdbc:mysql://localhost:3306/qiliblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

logging:
  level:
    com.zqqiliyc: debug
    web: info
    sql: debug